In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("D:\\Gen AI\\employee_sample_dataset.csv")
df

   EmpID     Name Department  Age  Salary  Experience        City
0    101     Arun         IT   25   35000           2     Chennai
1    102    Priya         HR   29   42000           5     Madurai
2    103    Kumar         IT   32   58000           8     Chennai
3    104    Divya    Finance   27   39000           3  Coimbatore
4    105    Rahul         IT   24   30000           1       Salem
5    106    Meena         HR   35   62000          10     Chennai
6    107  Sathish    Finance   31   51000           7     Madurai
7    108     Nila         IT   28   47000           4  Coimbatore
8    109    Vijay      Sales   30   44000           6     Chennai
9    110    Kavya      Sales   26   36000           2       Salem

In [3]:
df.to_csv("employee_data.csv",index = False)

###  **1.Create a Pandas DataFrame from the sample dataset. Display the first 5 rows, last 3 rows, the number of rows and columns, and the column data types.**

In [4]:
df = pd.read_csv("employee_data.csv")
df

   EmpID     Name Department  Age  Salary  Experience        City
0    101     Arun         IT   25   35000           2     Chennai
1    102    Priya         HR   29   42000           5     Madurai
2    103    Kumar         IT   32   58000           8     Chennai
3    104    Divya    Finance   27   39000           3  Coimbatore
4    105    Rahul         IT   24   30000           1       Salem
5    106    Meena         HR   35   62000          10     Chennai
6    107  Sathish    Finance   31   51000           7     Madurai
7    108     Nila         IT   28   47000           4  Coimbatore
8    109    Vijay      Sales   30   44000           6     Chennai
9    110    Kavya      Sales   26   36000           2       Salem

In [5]:
df.head(5)

   EmpID   Name Department  Age  Salary  Experience        City
0    101   Arun         IT   25   35000           2     Chennai
1    102  Priya         HR   29   42000           5     Madurai
2    103  Kumar         IT   32   58000           8     Chennai
3    104  Divya    Finance   27   39000           3  Coimbatore
4    105  Rahul         IT   24   30000           1       Salem

In [6]:
df.tail(3)

   EmpID   Name Department  Age  Salary  Experience        City
7    108   Nila         IT   28   47000           4  Coimbatore
8    109  Vijay      Sales   30   44000           6     Chennai
9    110  Kavya      Sales   26   36000           2       Salem

In [7]:
df.shape

(10, 7)

In [8]:
df.dtypes

EmpID         int64
Name            str
Department      str
Age           int64
Salary        int64
Experience    int64
City            str
dtype: object

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmpID       10 non-null     int64
 1   Name        10 non-null     str
 2   Department  10 non-null     str
 3   Age         10 non-null     int64
 4   Salary      10 non-null     int64
 5   Experience  10 non-null     int64
 6   City        10 non-null     str
dtypes: int64(4), str(3)
memory usage: 692.0 bytes

### **2.Display the details of employees who work in the IT department and have a salary greater than 40,000.**

In [10]:
result = df[(df["Department"] == "IT") & (df["Salary"] > 40000)]
result

   EmpID   Name Department  Age  Salary  Experience        City
2    103  Kumar         IT   32   58000           8     Chennai
7    108   Nila         IT   28   47000           4  Coimbatore

### **3.Display all employees sorted by salary from highest to lowest. Show only Name, Department, and Salary.**

In [11]:
result1 = df.sort_values(by = "Salary", ascending=False)
result1[["Name","Department","Salary"]]

      Name Department  Salary
5    Meena         HR   62000
2    Kumar         IT   58000
6  Sathish    Finance   51000
7     Nila         IT   47000
8    Vijay      Sales   44000
1    Priya         HR   42000
3    Divya    Finance   39000
9    Kavya      Sales   36000
0     Arun         IT   35000
4    Rahul         IT   30000

### **4.Find the mean, maximum, minimum, and median salary. Also find the average age of all employees.**

In [12]:
print("Mean Salary:", df["Salary"].mean())
print("Maximum Salary:", df["Salary"].max())
print("Minimum Salary:", df["Salary"].min())
print("Median Salary:", df["Salary"].median())
print()
print("Average age of all employees")
print("Average Age:", df["Age"].mean())

Mean Salary: 44400.0
Maximum Salary: 62000
Minimum Salary: 30000
Median Salary: 43000.0

Average age of all employees
Average Age: 28.7

### **5.For each department, calculate the number of employees, average salary, and highest salary. Sort the result by average salary in descending order.**

In [13]:
df1 = df.groupby("Department").agg(
    EmployeeCount=("EmpID", "count"),
    AverageSalary=("Salary", "mean"),
    HighestSalary=("Salary", "max"))
df1 = df1.sort_values(by="AverageSalary", ascending=False)
df1

            EmployeeCount  AverageSalary  HighestSalary
Department
HR                      2        52000.0          62000
Finance                 2        45000.0          51000
IT                      4        42500.0          58000
Sales                   2        40000.0          44000

### **6.Create a new column named AnnualSalary by multiplying Salary by 12. Display Name, Salary, and AnnualSalary.**

In [14]:
df["AnnualSalary"] = df["Salary"] * 12
df[["Name", "Salary", "AnnualSalary"]]

      Name  Salary  AnnualSalary
0     Arun   35000        420000
1    Priya   42000        504000
2    Kumar   58000        696000
3    Divya   39000        468000
4    Rahul   30000        360000
5    Meena   62000        744000
6  Sathish   51000        612000
7     Nila   47000        564000
8    Vijay   44000        528000
9    Kavya   36000        432000

### **7.Make a copy of the DataFrame, set one employee's City value to missing, and add a duplicate row. Use Pandas to identify missing values, fill the missing City with 'Unknown', and remove duplicate rows.**

In [15]:
df_copy = df.copy()
df_copy.loc[0, "City"] = None

In [16]:
df_copy.isnull().sum()

EmpID           0
Name            0
Department      0
Age             0
Salary          0
Experience      0
City            1
AnnualSalary    0
dtype: int64

In [17]:
df_copy["City"] = df_copy["City"].fillna("Unknown")
df_copy = df_copy.drop_duplicates()

In [18]:
df_copy

,EmpID,Name,Department,Age,Salary,Experience,City,AnnualSalary
0,101,Arun,IT,25,35000,2,Unknown,420000
1,102,Priya,HR,29,42000,5,Madurai,504000
2,103,Kumar,IT,32,58000,8,Chennai,696000
3,104,Divya,Finance,27,39000,3,Coimbatore,468000
4,105,Rahul,IT,24,30000,1,Salem,360000
5,106,Meena,HR,35,62000,10,Chennai,744000
6,107,Sathish,Finance,31,51000,7,Madurai,612000
7,108,Nila,IT,28,47000,4,Coimbatore,564000
8,109,Vijay,Sales,30,44000,6,Chennai,528000
9,110,Kavya,Sales,26,36000,2,Salem,432000

### **8.Create a column named SalaryLevel: 'High' for salary greater than or equal to 50,000, 'Medium' for salary from 40,000 to 49,999, and 'Low' for salary below 40,000. Display Name, Salary, and SalaryLevel.**

In [19]:
def salary_level(salary):
    if salary >= 50000:
        return "High"
    elif salary >= 40000:
        return "Medium"
    else:
        return "Low"

df["SalaryLevel"] = df["Salary"].apply(salary_level)
df[["Name", "Salary", "SalaryLevel"]]

      Name  Salary SalaryLevel
0     Arun   35000         Low
1    Priya   42000      Medium
2    Kumar   58000        High
3    Divya   39000         Low
4    Rahul   30000         Low
5    Meena   62000        High
6  Sathish   51000        High
7     Nila   47000      Medium
8    Vijay   44000      Medium
9    Kavya   36000         Low

### **9.Create a marks DataFrame with columns EmpID and TrainingScore, containing scores for EmpID 101, 103, 105, 108, and 110. Merge it with the employee DataFrame using EmpID. Display all employees and their scores, including employees without a score.**

In [20]:
marks = pd.DataFrame({
    "EmpID": [101, 103, 105, 108, 110],
    "TrainingScore": [70, 90, 65, 80, 75]
})
rlt = pd.merge(df, marks, on="EmpID", how="left")

rlt[["EmpID", "Name", "TrainingScore"]]

   EmpID     Name  TrainingScore
0    101     Arun           70.0
1    102    Priya            NaN
2    103    Kumar           90.0
3    104    Divya            NaN
4    105    Rahul           65.0
5    106    Meena            NaN
6    107  Sathish            NaN
7    108     Nila           80.0
8    109    Vijay            NaN
9    110    Kavya           75.0

### **10.Find the department with the highest average salary. Then display the employees whose salary is above the overall average salary. Write 2–3 sentences explaining your findings.**

In [21]:
avg_salary = df.groupby("Department")["Salary"].mean()
print("Highest Average Salary Department:", avg_salary.idxmax())

Highest Average Salary Department: HR

In [22]:
overall_avg = df["Salary"].mean()
print("Overall Average Salary:", overall_avg)

Overall Average Salary: 44400.0

In [23]:
rlt1 = df[df["Salary"] > overall_avg]
rlt1[["Name", "Department", "Salary"]]

      Name Department  Salary
2    Kumar         IT   58000
5    Meena         HR   62000
6  Sathish    Finance   51000
7     Nila         IT   47000

##### ***#10 explanation***

* df.groupby("Department")["Salary"].mean() groups the DataFrame by the "Department" column and calculates the average (mean) salary for each department.
* .idxmax() finds and returns the index label (which is the department name) that has the maximum average salary value.
* df["Salary"].mean() computes the average salary across all employees in the entire dataset, regardless of their department.
* df[df["Salary"] > overall_avg] creates a filtered subset of the DataFrame (rlt1) containing only the rows where the employee's salary is strictly greater than the overall average (44400.0).
* rlt1[["Name", "Department", "Salary"]] selects and displays only specific columns (Name, Department, and Salary) for those filtered employees.