### **Python Pandas**

In [1]:
import pandas as pd

### **Pandas Series**

In [2]:
carname = pd.Series(["BMW","KIA","TATA","NISSAN"])
carname

0       BMW
1       KIA
2      TATA
3    NISSAN
dtype: str

In [4]:
print(carname.dtype)
print(carname.shape)
print(carname.size)

str
(4,)
4

In [5]:
carname.info()

<class 'pandas.Series'>
RangeIndex: 4 entries, 0 to 3
Series name: None
Non-Null Count  Dtype
--------------  -----
4 non-null      str
dtypes: str(1)
memory usage: 164.0 bytes

In [6]:
carcolour = pd.Series(["Red","Black","Grey"])
carcolour

0      Red
1    Black
2     Grey
dtype: str

In [7]:
cardata = pd.DataFrame({
    "Name":carname,
    "Colour":carcolour
})
cardata

     Name Colour
0     BMW    Red
1     KIA  Black
2    TATA   Grey
3  NISSAN    NaN

In [8]:
print(cardata.dtypes)
print("------------")
print(cardata.shape)
print("------------")
print(cardata.size)

Name      str
Colour    str
dtype: object
------------
(4, 2)
------------
8

In [9]:
cardata.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Colour  3 non-null      str
dtypes: str(2)
memory usage: 196.0 bytes

In [22]:
cardata.isna().sum()

Name      0
Colour    1
dtype: int64

In [23]:
cardata.notna().sum()

Name      4
Colour    3
dtype: int64

In [10]:
studentname = pd.Series(["Pradeep","Ram","Arjun","Arun"])
studentname

0    Pradeep
1        Ram
2      Arjun
3       Arun
dtype: str

In [11]:
studentcourse = pd.Series(["GenAI","Data Analytics","DEVOpp","Networking"])
studentcourse

0             GenAI
1    Data Analytics
2            DEVOpp
3        Networking
dtype: str

In [12]:
data = pd.DataFrame({
    "Name":studentname,
    "Course":studentcourse
})
data

      Name          Course
0  Pradeep           GenAI
1      Ram  Data Analytics
2    Arjun          DEVOpp
3     Arun      Networking

In [13]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Course  4 non-null      str
dtypes: str(2)
memory usage: 196.0 bytes

In [14]:
df = pd.read_csv("D:\\Gen AI\\car_sales.csv")
df

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [15]:
df.to_csv("Test.csv",index=False)

In [16]:
new_df = pd.read_csv("Test.csv")
new_df

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [17]:
print(new_df.dtypes)

Make               str
Colour             str
Odometer (KM)    int64
Doors            int64
Price              str
dtype: object

In [18]:
new_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     str
 1   Colour         10 non-null     str
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     str
dtypes: int64(2), str(3)
memory usage: 532.0 bytes

In [25]:
new_df.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [26]:
new_df.describe()

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

### **Head and Tail**

In [28]:
new_df.head(6)

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00

In [30]:
new_df.tail(2)

     Make Colour  Odometer (KM)  Doors      Price
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

 ### **loc and iloc**

In [32]:
new_df.loc[2]

Make                Toyota
Colour                Blue
Odometer (KM)        32549
Doors                    3
Price            $7,000.00
Name: 2, dtype: object

In [39]:
carname = pd.Series(["BMW","KIA","TATA","NISSAN"],index = [5,6,7,8])
carname

5       BMW
6       KIA
7      TATA
8    NISSAN
dtype: str

In [41]:
carname.loc[5:7]

5     BMW
6     KIA
7    TATA
dtype: str

In [43]:
carname.iloc[0:10]

5       BMW
6       KIA
7      TATA
8    NISSAN
dtype: str

In [44]:
new_df

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

### **Columns**

In [45]:
new_df.Make

0    Toyota
1     Honda
2    Toyota
3       BMW
4    Nissan
5    Toyota
6     Honda
7     Honda
8    Toyota
9    Nissan
Name: Make, dtype: str

In [46]:
new_df["Colour"]

0    White
1      Red
2     Blue
3    Black
4    White
5    Green
6     Blue
7     Blue
8    White
9    White
Name: Colour, dtype: str

In [47]:
new_df["Make"].value_counts()

Make
Toyota    4
Honda     3
Nissan    2
BMW       1
Name: count, dtype: int64